service: serverless-quod-screenshotter

frameworkVersion: '>=2.13.0 <3.0.0'

custom:
  stage: ${opt:stage, 'stage'}

  s3:
    responseRegion: 'eu-west-2'
    responseBucket: 'uploads.atmos.dreamm.co.uk'

  cors:
    origin: '*'
    headers:
      - Accept-Encoding
      - Content-Type
      - Content-Length
      - X-Amz-Date
      - Authorization
      - X-Api-Key
      - X-Amz-Security-Token
      - X-Amz-User-Agent
      - Access-Control-Allow-Origin
      - Access-Control-Allow-Headers
      - Access-Control-Allow-Methods
    allowCredentials: false

  apigwBinary:
    types:
      - '*/*'

provider:
  name: aws
  region: eu-west-2
  runtime: nodejs12.x
  logRetentionInDays: 90
  deploymentBucket: dreamm-pdf-serverless-deployments

  environment:
    NODE_ENV: ${self:custom.stage}
    S3_LARGE_HTTP_RESPONSE_REGION: ${self:custom.s3.responseRegion}
    S3_LARGE_HTTP_RESPONSE_BUCKET: ${self:custom.s3.responseBucket}

  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:GetObject
        - s3:PutObject
      Resource: arn:aws:s3:::${self:custom.s3.responseBucket}/*

  apiGateway:
    shouldStartNameWithService: true

package:
  individually: true

layers:
  HeadlessChromium:
    name: serverless-headless-chromium-${self:custom.stage}-v88
    description: Layer for puppeteer to launch headless Chromium v88
    compatibleRuntimes:
      - nodejs12.x
    package:
      artifact: layers/chromium-v88.zip

functions:
  print:
    handler: print/print.handler
    description: Generates a PDF from HTML (using Chromium v88)
    memorySize: 1536
    timeout: 300
    layers:
      - { Ref: HeadlessChromiumLambdaLayer }
    events:
      - http:
          path: /print
          method: POST
          cors: ${self:custom.cors}

resources:
  Description: API for generating PDF from HTML

plugins:
  - serverless-webpack
  - serverless-apigw-binary
